parameters:
- name: component
  values: 
    - DSO
    - FDDG
    - DAM
    - DSFP
- name: componentSuffix
  type: string
  default: ''
- name: environment
  type: string
- name: serverName
  type: string
- name: iisSiteFolderPrefix
  type: string
- name: applicationPoolPrefix
  type: string

jobs:
- deployment: Deploy${{ parameters.component }}${{ parameters.componentSuffix }}To${{ parameters.environment }}Server
  displayName: "Deploy ${{ parameters.component }}${{ parameters.componentSuffix }} to ${{ parameters.environment }} server"
  environment: ${{ parameters.environment }} 
  variables:
    componentName: ${{ parameters.component }}${{ parameters.componentSuffix }}
    applicationPoolName: ${{ parameters.applicationPoolPrefix }}${{ var.componentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: deployPackage
        - task: PowerShellOnTargetMachines@3
          displayName: "Stop IIS application pool $(applicationPoolName) on ${{ parameters.environment }} server"
          inputs:
            Machines: ${{ parameters.serverName }}
            UserName: $(DeployUserName)
            UserPassword: $(DeployUserPassword)
            InlineScript: |
              if((Get-WebAppPoolState $(applicationPoolName)).Value -eq 'Started') { Stop-WebAppPool $(applicationPoolName) }
        - task: WindowsMachineFileCopy@2
          displayName: "Deploy $(componentName) application files to ${{ parameters.environment }} server"
          inputs:
            SourcePath: "$(Pipeline.Workspace)/deployPackage/${{ parameters.component }}"
            MachineNames: ${{ parameters.serverName }}
            AdminUserName: $(DeployUserName)
            AdminPassword: $(DeployUserPassword)
            TargetPath: "${{ parameters.iisSiteFolderPrefix }}$(componentName)"
            CleanTargetBeforeCopy: true
        - task: PowerShellOnTargetMachines@3
          displayName: "Start IIS application pool $(applicationPoolName) on ${{ parameters.environment }} server"
          inputs:
            Machines: ${{ parameters.serverName }}
            UserName: $(DeployUserName)
            UserPassword: $(DeployUserPassword)
            InlineScript: "Start-WebAppPool $(applicationPoolName)" 