parameters:
- name: component
  values: 
    - DSO
    - FDDG
    - DAM
    - DSFO
- name: componentSuffix
  type: string
  default: ''
- name: environment
  type: string
- name: serverName
  type: string
- name: iisSiteName
  type: string
- name: iisSiteFolderPrefix
  type: string
- name: applicationPoolPrefix
  type: string
  # temporary parameter obsolete when all components use mustache for config
- name: useMustacheForConfig
  type: boolean
  default: false
  # make required when every component uses mustache
- name: docSysConfigurationFilePath
  type: string
  default: ''

jobs:
- deployment: Deploy${{ parameters.component }}${{ parameters.componentSuffix }}To${{ parameters.environment }}Server
  displayName: "Deploy ${{ parameters.component }}${{ parameters.componentSuffix }} to ${{ parameters.environment }} server"
  workspace:
    clean: all
  environment: ${{ parameters.environment }} 
  variables:
    componentName: ${{ parameters.component }}${{ parameters.componentSuffix }}
    applicationPoolName: ${{ parameters.applicationPoolPrefix }}$(componentName)
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          displayName: 'Download deploy package'
          artifact: deployPackage
        - download: current
          displayName: 'Download scripts'
          artifact: scripts
        - download: current
          displayName: 'Download configuration'
          artifact: config
        - task: WindowsMachineFileCopy@2
          displayName: "Deploy scripts to ${{ parameters.environment }} server"
          inputs:
            SourcePath: "$(Pipeline.Workspace)/scripts"
            MachineNames: ${{ parameters.serverName }}
            AdminUserName: $(DeployUserName)
            AdminPassword: $(DeployUserPassword)
            TargetPath: "${{ parameters.iisSiteFolderPrefix }}Scripts"
            CleanTargetBeforeCopy: true
        - task: PowerShell@2
          displayName: "Configure configuration files with Mustache in deployment staging directory"
          condition: ${{ eq(parameters.useMustacheForConfig, true) }}
          inputs:
            targetType: filePath
            filePath: $(Pipeline.Workspace)\scripts\ConfigureConfigurationFilesWithMustache.ps1
            workingDirectory: "$(Pipeline.Workspace)/deployPackage/${{ parameters.component }}"
            arguments: '-docSysConfigurationFilePath $(Pipeline.Workspace)\config\${{ parameters.docSysConfigurationFilePath }}'
        - task: PowerShell@2
          displayName: "Copy selected plugin files to deployment staging directory"
          inputs:
            targetType: filePath
            filePath: $(Pipeline.Workspace)\scripts\CopySelectedPluginsToDeploymentStagingDirectory.ps1
            workingDirectory: "$(Pipeline.Workspace)/deployPackage"
            arguments: '-docSysConfigurationFilePath $(Pipeline.Workspace)\config\${{ parameters.docSysConfigurationFilePath }} -component ${{ parameters.component }}'
        - task: PowerShellOnTargetMachines@3
          displayName: "Stop IIS application pool $(applicationPoolName) on ${{ parameters.environment }} server"
          inputs:
            Machines: ${{ parameters.serverName }}
            UserName: $(DeployUserName)
            UserPassword: $(DeployUserPassword)
            InlineScript: |
              if((Get-WebAppPoolState $(applicationPoolName)).Value -eq 'Started') { Stop-WebAppPool $(applicationPoolName) }
        - task: WindowsMachineFileCopy@2
          displayName: "Deploy $(componentName) application files to ${{ parameters.environment }} server"
          inputs:
            SourcePath: "$(Pipeline.Workspace)/deployPackage/${{ parameters.component }}"
            MachineNames: ${{ parameters.serverName }}
            AdminUserName: $(DeployUserName)
            AdminPassword: $(DeployUserPassword)
            TargetPath: "${{ parameters.iisSiteFolderPrefix }}$(componentName)"
            CleanTargetBeforeCopy: true
        - task: PowerShellOnTargetMachines@3
          condition: ${{ eq(parameters.useMustacheForConfig, false) }}
          displayName: "Copy config"
          inputs:
            Machines: ${{ parameters.serverName }}
            UserName: $(DeployUserName)
            UserPassword: $(DeployUserPassword)
            InlineScript: |
              Copy-Item -Path "${{ parameters.iisSiteFolderPrefix }}Config\$(componentName)\*" -Destination "${{ parameters.iisSiteFolderPrefix }}$(componentName)" -Recurse -Force
        - task: PowerShellOnTargetMachines@3
          displayName: "Clear Temporary ASP.Net files cache on ${{ parameters.environment }} server"
          inputs:
            Machines: ${{ parameters.serverName }}
            UserName: $(DeployUserName)
            UserPassword: $(DeployUserPassword)
            ScriptType: FilePath
            ScriptPath: ${{ parameters.iisSiteFolderPrefix }}/Scripts/ClearTemporaryASPNetFilesForIISSite.ps1
            ScriptArguments: '-iisSiteName UWV'
        - task: PowerShellOnTargetMachines@3
          displayName: "Start IIS application pool $(applicationPoolName) on ${{ parameters.environment }} server"
          inputs:
            Machines: ${{ parameters.serverName }}
            UserName: $(DeployUserName)
            UserPassword: $(DeployUserPassword)
            InlineScript: "Start-WebAppPool $(applicationPoolName)" 